name: ihome
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.15.1 <3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  google_fonts: ^2.1.0
  intl: ^0.18.0
  path: ^1.8.0
  uuid: ^3.0.4
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_vibrate: ^1.1.0
  location: ^4.2.0
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.2
  http: ^0.13.3
  package_info_plus: ^3.1.2
  flutter_plugin_android_lifecycle: ^2.0.5
  lint: ^1.0.0
  flex_color_picker: ^2.2.0
  pull_to_refresh: ^2.0.0
  reflectable: ^3.0.4
  wheel_chooser: ^1.0.0
  screen_brightness: ^0.1.3
  wakelock: ^0.6.2
  modal_bottom_sheet: 
    path: ./packages/modal_bottom_sheet-master/
  socket_io_client: ^2.0.1
  flutter_bloc: ^8.1.1
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  firebase_crashlytics: ^3.0.10
  shared_preferences: ^2.0.16
  settings_bundle: ^0.0.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  remove_alpha_ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family:  CustomIcons  
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: SFCompact
      fonts:
        - asset: assets/fonts/SF-Compact-Text-Ultralight.otf
          weight: 100
        - asset: assets/fonts/SF-Compact-Text-Thin.otf
          weight: 200
        - asset: assets/fonts/SF-Compact-Text-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Compact-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Compact-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Compact-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Compact-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Compact-Text-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Compact-Text-Black.otf
          weight: 900



flutter_intl:
  enabled: true
