// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcBNzicuVCEP4uNBKwXyBYh6ZgFBPd52E',
    appId: '1:1048524991219:web:9216c3c0ac286e95e4e586',
    messagingSenderId: '1048524991219',
    projectId: 'ihome-45f64',
    authDomain: 'ihome-45f64.firebaseapp.com',
    storageBucket: 'ihome-45f64.appspot.com',
    measurementId: 'G-62GHY78BC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj2RHSCOOuNa-IinGY3dMkTlqEx75cZuQ',
    appId: '1:1048524991219:android:4c917186852c3540e4e586',
    messagingSenderId: '1048524991219',
    projectId: 'ihome-45f64',
    storageBucket: 'ihome-45f64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDccNE3vQg2MDwFbYoQgyrRJbgLbdnpids',
    appId: '1:1048524991219:ios:c1877c8444134848e4e586',
    messagingSenderId: '1048524991219',
    projectId: 'ihome-45f64',
    storageBucket: 'ihome-45f64.appspot.com',
    iosClientId: '1048524991219-2voj3ctf1n2b1kq9u0i97b8csboi3bmq.apps.googleusercontent.com',
    iosBundleId: 'com.example.ihome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDccNE3vQg2MDwFbYoQgyrRJbgLbdnpids',
    appId: '1:1048524991219:ios:c1877c8444134848e4e586',
    messagingSenderId: '1048524991219',
    projectId: 'ihome-45f64',
    storageBucket: 'ihome-45f64.appspot.com',
    iosClientId: '1048524991219-2voj3ctf1n2b1kq9u0i97b8csboi3bmq.apps.googleusercontent.com',
    iosBundleId: 'com.example.ihome',
  );
}
